{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-finch
  version: {{ version|replace("-", "_") }}

source:
  fn: finch_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/finch_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/finch/finch_{{ version }}.tar.gz
  sha256: 02acd8624772b303eab85db3fbe009c8026981edc65f9b7d017433b006f6f4b1

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-eml >=1.0.1
    - r-data.table >=1.10.0
    - r-digest
    - r-hoardr >=0.2.0
    - r-plyr
    - r-rappdirs
    - r-xml2 >=1.0.0
  run:
    - r-base
    - r-eml >=1.0.1
    - r-data.table >=1.10.0
    - r-digest
    - r-hoardr >=0.2.0
    - r-plyr
    - r-rappdirs
    - r-xml2 >=1.0.0

test:
  commands:
    - $R -e "library('finch')"           # [not win]
    - "\"%R%\" -e \"library('finch')\""  # [win]

about:
  home: https://github.com/ropensci/finch
  license: MIT
  license_file: LICENSE
  summary: Parse and create Darwin Core (<http://rs.tdwg.org/dwc/>) Simple and Archives. Functionality
    includes reading and parsing all the files in a Darwin Core Archive, including the
    datasets and metadata; read and parse simple Darwin Core files; and validation of
    Darwin Core Archives.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
