{% set version = '0.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-finch
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/finch_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/finch/finch_{{ version }}.tar.gz
  sha256: 02acd8624772b303eab85db3fbe009c8026981edc65f9b7d017433b006f6f4b1

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-eml >=2.0.0
    - r-data.table >=1.10.0
    - r-digest
    - r-hoardr >=0.2.0
    - r-plyr
    - r-rappdirs
    - r-xml2 >=1.0.0
  run:
    - r-base
    - r-eml >=2.0.0
    - r-data.table >=1.10.0
    - r-digest
    - r-hoardr >=0.2.0
    - r-plyr
    - r-rappdirs
    - r-xml2 >=1.0.0

test:
  commands:
    - $R -e "library('finch')"           # [not win]
    - "\"%R%\" -e \"library('finch')\""  # [win]

about:
  home: https://github.com/ropensci/finch
  license: MIT
  license_file: LICENSE
  summary: Parse and create Darwin Core (<http://rs.tdwg.org/dwc/>) Simple and Archives. Functionality
    includes reading and parsing all the files in a Darwin Core Archive, including the
    datasets and metadata; read and parse simple Darwin Core files; and validation of
    Darwin Core Archives.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: finch
# Title: Parse Darwin Core Files
# Description: Parse and create Darwin Core (<http://rs.tdwg.org/dwc/>) Simple and Archives. Functionality includes reading and parsing all the files in a Darwin Core Archive, including the datasets and metadata; read and parse simple Darwin Core files; and validation of Darwin Core Archives.
# Version: 0.3.0
# Authors@R: person("Scott", "Chamberlain", role = c("aut", "cre"), email = "myrmecocystus@gmail.com", comment = c(ORCID = "0000-0003-1444-9135"))
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/ropensci/finch
# BugReports: https://github.com/ropensci/finch/issues
# Encoding: UTF-8
# Imports: xml2 (>= 1.0.0), EML (>= 2.0.0), data.table (>= 1.10.0), plyr, rappdirs, digest, hoardr (>= 0.2.0)
# Suggests: testthat, crul, jsonlite
# RoxygenNote: 6.1.1
# X-schema.org-applicationCategory: Biology
# X-schema.org-keywords: biology, occurrences, specimen, biodiversity, collections, species
# X-schema.org-isPartOf: https://ropensci.org
# NeedsCompilation: no
# Packaged: 2019-04-24 20:16:30 UTC; sckott
# Author: Scott Chamberlain [aut, cre] (<https://orcid.org/0000-0003-1444-9135>)
# Maintainer: Scott Chamberlain <myrmecocystus@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-04-25 05:20:13 UTC
