{% set version = "0.2.0" %}

package:
  name: r-finch
  version: {{ version }}

source:
  fn: finch_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/finch_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/finch/finch_{{ version }}.tar.gz
  sha256: 55d6513c686b69eb5f145a736d072fa7b0acf004383829beeb2635f1e7b2eaed

build:
  number: 0
  skip: True  # [win32]
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-eml >=1.0.1
    - r-data.table >=1.10.0
    - r-digest
    - r-plyr
    - r-rappdirs
    - r-xml2 >=1.0.0
  run:
    - r-base
    - r-eml >=1.0.1
    - r-data.table >=1.10.0
    - r-digest
    - r-plyr
    - r-rappdirs
    - r-xml2 >=1.0.0

test:
  commands:
    - R -e "library('finch')"  # [not win]
    - R -e \"library('finch')\"  # [win]

about:
  home: https://github.com/ropensci/finch
  license: MIT
  license_file: LICENSE
  summary: 'Read Darwin Core Archive files'

extra:
  recipe-maintainers:
    - ocefpaf
