travis:
  secure:
    BINSTAR_TOKEN: dgsOSnebJ7GAqz/aRroIaBrES6F2izgqWgaeMxrwNbiPfJVTrBo0LaW1EF4OD3jHNzrRMN6ROxySzS6zt8km84XRzSke9hCfnRMgV0iVgavalTk+cRH3bJ3BLr7l6qgf8cF1N7nqjyuEc2DabnjlfHDOZs7RBdNkltbM9eLOFZ2XUkFd8ANhG8ngJ/SMskmMIVXqy/QdN8KML0WrSiB82aGrN0Fmleqb6oEcfiQ5xJ34UNk8/pbKEx5pc9goPiPHRDwTcZmQXNyyIuBas+2zWf0aAFJMKzcwp3rIWbzv1VTIjPOlMG05SvEngfqpYECzE6Bs+2dA+qOBbRQpy2oub5v01SBD4torNI6XXDMeE+R76dF0nthcBsXBpXgeE+UGueJ0x8p6yzh4xKjr7EOKX0o+Yr3sXHOW02r8XG3Wf9JKerua0vFMebAGLLarkZl9fQYqJf3QrDvKlYebbp61H/D+ohfGgtNRh+VwPCSoAU+f5ZTbpAdQbLE+gZRrwur88XmUVLpkCSksd4KoLXnvD0w4CJyUwfMUX/9sBs2GDU3zE/RpjpQxZWPNCvYoWxwlQFcLGEHRSQATp+aDSd2FB31jSbYX/opOTheGiONC02PzJru6gapOfO2NuL/BiYIOt6DznYI+8apaRY+KADJmCILirIv5TR0y5GhGeuK8624=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
